# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

profile_research_task:
  description: >
    Conduct a thorough analysis of GitHub user @{username}'s profile.
    Extract information about their public repositories (name, description,
    languages, stars, forks), contribution activity (commits, pull requests,
    issues to their own and other repos), and profile details (bio, location,
    website, organizations).
  expected_output: >
    A structured summary of the user's GitHub profile, including a list of
    key repositories with their details, contribution statistics, and relevant
    profile information.
  agent: github_profile_researcher

resume_generation_task:
  description: >
    Using the GitHub profile research, generate a professional CV/Resume
    for @{username} in Markdown format. The resume should include sections like
    Summary/Objective, Skills (derived from languages and project descriptions),
    Projects (highlighting 2-3 key repositories), and Contributions.
  expected_output: >
    A well-formatted Markdown document representing the user's CV/Resume.
    The resume should be professional, concise, and accurately reflect the
    gathered data. DO NOT embed the output in a ```markdown block. Just raw markdown.
    Make sure there are no thoughts or planning in the output, just the resume.
  agent: resume_writer
